name = "TheForce"
uuid = "fbee0d66-0c7b-49c9-8172-283e09681d64"
authors = ["Steve Hughes"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
