name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: test-${{ matrix.pkg }}-julia-${{ matrix.julia }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia: ['1.10', '1.11', '1.12']
        pkg: [TheForce, TheEmpire, TheResistance, StarWarsApp]
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ matrix.pkg }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia }}

      - name: Instantiate (workspace on 1.12; path-deps otherwise)
        shell: bash
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.activate(".")
            if VERSION < v"1.12"
              pkg = basename(pwd())
              # Always develop TheForce for dependents
              if pkg != "TheForce"; Pkg.develop(path=joinpath(pwd(), "..", "TheForce")); end
              if pkg == "StarWarsApp"
                Pkg.develop(path=joinpath(pwd(), "..", "TheEmpire"))
                Pkg.develop(path=joinpath(pwd(), "..", "TheResistance"))
              end
            end
            Pkg.instantiate()
          '

      - name: Test with coverage
        run: julia --project=. --code-coverage=user -e 'using Pkg; Pkg.test(coverage=true)'

      - name: LCOV artifact
        run: julia --project=. -e 'using Coverage; LCOV.writefile(joinpath(ENV["GITHUB_WORKSPACE"], "lcov-${{ matrix.pkg }}.info"), process_folder("src"))'
        
      - uses: actions/upload-artifact@v4
        with:
          name: lcov-${{ matrix.pkg }}
          path: lcov-${{ matrix.pkg }}.info